---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-cloud-antrea-io-v1alpha1-cloudentityselector
  failurePolicy: Fail
  name: mcloudentityselector.kb.io
  rules:
  - apiGroups:
    - crd.cloud.antrea.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudentityselectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-cloud-antrea-io-v1alpha1-cloudprovideraccount
  failurePolicy: Fail
  name: mcloudprovideraccount.kb.io
  rules:
  - apiGroups:
    - crd.cloud.antrea.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - cloudprovideraccounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crd-cloud-antrea-io-v1alpha1-virtualmachine
  failurePolicy: Fail
  name: mvirtualmachine.kb.io
  rules:
  - apiGroups:
    - crd.cloud.antrea.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-cloud-antrea-io-v1alpha1-cloudentityselector
  failurePolicy: Fail
  name: vcloudentityselector.kb.io
  rules:
  - apiGroups:
    - crd.cloud.antrea.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudentityselectors
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-cloud-antrea-io-v1alpha1-cloudprovideraccount
  failurePolicy: Fail
  name: vcloudprovideraccount.kb.io
  rules:
  - apiGroups:
    - crd.cloud.antrea.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudprovideraccounts
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crd-cloud-antrea-io-v1alpha1-virtualmachine
  failurePolicy: Fail
  name: vvirtualmachine.kb.io
  rules:
  - apiGroups:
    - crd.cloud.antrea.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
