# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.crd.cloud.antrea.io
spec:
  preserveUnknownFields: False
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: [ "v1","v1beta1" ]
      clientConfig:
      # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
      # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
        caBundle: Cg==
        service:
          name: nephe-controller-webhook-service
          namespace: system
          path: /convert
